// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(yniffiFFI)
    import yniffiFFI
#endif

private extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_yniffi_7ef6_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_yniffi_7ef6_rustbuffer_free(self, $0) }
    }
}

private extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

private extension Data {
    init(rustBuffer: RustBuffer) {
        // TODO: This copies the buffer. Can we read directly from a
        // Rust buffer?
        self.init(bytes: rustBuffer.data!, count: Int(rustBuffer.len))
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

private func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
private func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset ..< reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value) { reader.data.copyBytes(to: $0, from: range) }
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
private func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> [UInt8] {
    let range = reader.offset ..< (reader.offset + count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer { buffer in
        reader.data.copyBytes(to: buffer, from: range)
    }
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
private func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return try Float(bitPattern: readInt(&reader))
}

// Reads a float at the current offset.
private func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return try Double(bitPattern: readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
private func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

private func createWriter() -> [UInt8] {
    return []
}

private func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
private func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

private func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

private func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous go the Rust trait of the same name.
private protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
private protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType {}

extension FfiConverterPrimitive {
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
private protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

    public static func lower(_ value: SwiftType) -> RustBuffer {
        var writer = createWriter()
        write(value, into: &writer)
        return RustBuffer(bytes: writer)
    }
}

// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
private enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

private let CALL_SUCCESS: Int8 = 0
private let CALL_ERROR: Int8 = 1
private let CALL_PANIC: Int8 = 2

private extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: {
        $0.deallocate()
        return UniffiInternalError.unexpectedRustCallError
    })
}

private func rustCallWithError<T, F: FfiConverter>
(_ errorFfiConverter: F.Type, _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T
    where F.SwiftType: Error, F.FfiType == RustBuffer
{
    try makeRustCall(callback, errorHandler: { try errorFfiConverter.lift($0) })
}

private func makeRustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T, errorHandler: (RustBuffer) throws -> Error) throws -> T {
    var callStatus = RustCallStatus()
    let returnedVal = callback(&callStatus)
    switch callStatus.code {
    case CALL_SUCCESS:
        return returnedVal

    case CALL_ERROR:
        throw try errorHandler(callStatus.errorBuf)

    case CALL_PANIC:
        // When the rust code sees a panic, it tries to construct a RustBuffer
        // with the message.  But if that code panics, then it just sends back
        // an empty buffer.
        if callStatus.errorBuf.len > 0 {
            throw try UniffiInternalError.rustPanic(FfiConverterString.lift(callStatus.errorBuf))
        } else {
            callStatus.errorBuf.deallocate()
            throw UniffiInternalError.rustPanic("Rust panic")
        }

    default:
        throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

// Public interface members begin here.

private struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

private struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

private struct FfiConverterBool: FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

private struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return try String(bytes: readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

public protocol YrsArrayProtocol {
    func each(tx: YrsTransaction, delegate: YrsArrayEachDelegate)
    func get(tx: YrsTransaction, index: UInt32) throws -> String
    func insert(tx: YrsTransaction, index: UInt32, value: String)
    func insertRange(tx: YrsTransaction, index: UInt32, values: [String])
    func length(tx: YrsTransaction) -> UInt32
    func pushBack(tx: YrsTransaction, value: String)
    func pushFront(tx: YrsTransaction, value: String)
    func remove(tx: YrsTransaction, index: UInt32)
    func removeRange(tx: YrsTransaction, index: UInt32, len: UInt32)
    func toA(tx: YrsTransaction) -> [String]
    func observe(delegate: YrsArrayObservationDelegate) -> UInt32
    func unobserve(subscriptionId: UInt32)
}

public class YrsArray: YrsArrayProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    deinit {
        try! rustCall { ffi_yniffi_7ef6_YrsArray_object_free(pointer, $0) }
    }

    public func each(tx: YrsTransaction, delegate: YrsArrayEachDelegate) {
        try!
            rustCall {
                yniffi_7ef6_YrsArray_each(self.pointer,
                                          FfiConverterTypeYrsTransaction.lower(tx),
                                          FfiConverterCallbackInterfaceYrsArrayEachDelegate.lower(delegate), $0)
            }
    }

    public func get(tx: YrsTransaction, index: UInt32) throws -> String {
        return try FfiConverterString.lift(
            rustCallWithError(FfiConverterTypeCodingError.self) {
                yniffi_7ef6_YrsArray_get(self.pointer,
                                         FfiConverterTypeYrsTransaction.lower(tx),
                                         FfiConverterUInt32.lower(index), $0)
            }
        )
    }

    public func insert(tx: YrsTransaction, index: UInt32, value: String) {
        try!
            rustCall {
                yniffi_7ef6_YrsArray_insert(self.pointer,
                                            FfiConverterTypeYrsTransaction.lower(tx),
                                            FfiConverterUInt32.lower(index),
                                            FfiConverterString.lower(value), $0)
            }
    }

    public func insertRange(tx: YrsTransaction, index: UInt32, values: [String]) {
        try!
            rustCall {
                yniffi_7ef6_YrsArray_insert_range(self.pointer,
                                                  FfiConverterTypeYrsTransaction.lower(tx),
                                                  FfiConverterUInt32.lower(index),
                                                  FfiConverterSequenceString.lower(values), $0)
            }
    }

    public func length(tx: YrsTransaction) -> UInt32 {
        return try! FfiConverterUInt32.lift(
            try!
                rustCall {
                    yniffi_7ef6_YrsArray_length(self.pointer,
                                                FfiConverterTypeYrsTransaction.lower(tx), $0)
                }
        )
    }

    public func pushBack(tx: YrsTransaction, value: String) {
        try!
            rustCall {
                yniffi_7ef6_YrsArray_push_back(self.pointer,
                                               FfiConverterTypeYrsTransaction.lower(tx),
                                               FfiConverterString.lower(value), $0)
            }
    }

    public func pushFront(tx: YrsTransaction, value: String) {
        try!
            rustCall {
                yniffi_7ef6_YrsArray_push_front(self.pointer,
                                                FfiConverterTypeYrsTransaction.lower(tx),
                                                FfiConverterString.lower(value), $0)
            }
    }

    public func remove(tx: YrsTransaction, index: UInt32) {
        try!
            rustCall {
                yniffi_7ef6_YrsArray_remove(self.pointer,
                                            FfiConverterTypeYrsTransaction.lower(tx),
                                            FfiConverterUInt32.lower(index), $0)
            }
    }

    public func removeRange(tx: YrsTransaction, index: UInt32, len: UInt32) {
        try!
            rustCall {
                yniffi_7ef6_YrsArray_remove_range(self.pointer,
                                                  FfiConverterTypeYrsTransaction.lower(tx),
                                                  FfiConverterUInt32.lower(index),
                                                  FfiConverterUInt32.lower(len), $0)
            }
    }

    public func toA(tx: YrsTransaction) -> [String] {
        return try! FfiConverterSequenceString.lift(
            try!
                rustCall {
                    yniffi_7ef6_YrsArray_to_a(self.pointer,
                                              FfiConverterTypeYrsTransaction.lower(tx), $0)
                }
        )
    }

    public func observe(delegate: YrsArrayObservationDelegate) -> UInt32 {
        return try! FfiConverterUInt32.lift(
            try!
                rustCall {
                    yniffi_7ef6_YrsArray_observe(self.pointer,
                                                 FfiConverterCallbackInterfaceYrsArrayObservationDelegate.lower(delegate), $0)
                }
        )
    }

    public func unobserve(subscriptionId: UInt32) {
        try!
            rustCall {
                yniffi_7ef6_YrsArray_unobserve(self.pointer,
                                               FfiConverterUInt32.lower(subscriptionId), $0)
            }
    }
}

public struct FfiConverterTypeYrsArray: FfiConverter {
    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = YrsArray

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> YrsArray {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if ptr == nil {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: YrsArray, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> YrsArray {
        return YrsArray(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: YrsArray) -> UnsafeMutableRawPointer {
        return value.pointer
    }
}

public protocol YrsDocProtocol {
    func encodeDiffV1(tx: YrsTransaction, stateVector: [UInt8]) throws -> [UInt8]
    func getText(name: String) -> YrsText
    func getArray(name: String) -> YrsArray
    func getMap(name: String) -> YrsMap
    func transact() -> YrsTransaction
}

public class YrsDoc: YrsDocProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    public convenience init() {
        self.init(unsafeFromRawPointer: try!

            rustCall {
                yniffi_7ef6_YrsDoc_new($0)
            })
    }

    deinit {
        try! rustCall { ffi_yniffi_7ef6_YrsDoc_object_free(pointer, $0) }
    }

    public func encodeDiffV1(tx: YrsTransaction, stateVector: [UInt8]) throws -> [UInt8] {
        return try FfiConverterSequenceUInt8.lift(
            rustCallWithError(FfiConverterTypeCodingError.self) {
                yniffi_7ef6_YrsDoc_encode_diff_v1(self.pointer,
                                                  FfiConverterTypeYrsTransaction.lower(tx),
                                                  FfiConverterSequenceUInt8.lower(stateVector), $0)
            }
        )
    }

    public func getText(name: String) -> YrsText {
        return try! FfiConverterTypeYrsText.lift(
            try!
                rustCall {
                    yniffi_7ef6_YrsDoc_get_text(self.pointer,
                                                FfiConverterString.lower(name), $0)
                }
        )
    }

    public func getArray(name: String) -> YrsArray {
        return try! FfiConverterTypeYrsArray.lift(
            try!
                rustCall {
                    yniffi_7ef6_YrsDoc_get_array(self.pointer,
                                                 FfiConverterString.lower(name), $0)
                }
        )
    }

    public func getMap(name: String) -> YrsMap {
        return try! FfiConverterTypeYrsMap.lift(
            try!
                rustCall {
                    yniffi_7ef6_YrsDoc_get_map(self.pointer,
                                               FfiConverterString.lower(name), $0)
                }
        )
    }

    public func transact() -> YrsTransaction {
        return try! FfiConverterTypeYrsTransaction.lift(
            try!
                rustCall {
                    yniffi_7ef6_YrsDoc_transact(self.pointer, $0)
                }
        )
    }
}

public struct FfiConverterTypeYrsDoc: FfiConverter {
    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = YrsDoc

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> YrsDoc {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if ptr == nil {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: YrsDoc, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> YrsDoc {
        return YrsDoc(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: YrsDoc) -> UnsafeMutableRawPointer {
        return value.pointer
    }
}

public protocol YrsMapProtocol {
    func length(tx: YrsTransaction) -> UInt32
    func containsKey(tx: YrsTransaction, key: String) -> Bool
    func insert(tx: YrsTransaction, key: String, value: String)
    func get(tx: YrsTransaction, key: String) throws -> String
    func remove(tx: YrsTransaction, key: String) throws -> String?
    func clear(tx: YrsTransaction)
}

public class YrsMap: YrsMapProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    deinit {
        try! rustCall { ffi_yniffi_7ef6_YrsMap_object_free(pointer, $0) }
    }

    public func length(tx: YrsTransaction) -> UInt32 {
        return try! FfiConverterUInt32.lift(
            try!
                rustCall {
                    yniffi_7ef6_YrsMap_length(self.pointer,
                                              FfiConverterTypeYrsTransaction.lower(tx), $0)
                }
        )
    }

    public func containsKey(tx: YrsTransaction, key: String) -> Bool {
        return try! FfiConverterBool.lift(
            try!
                rustCall {
                    yniffi_7ef6_YrsMap_contains_key(self.pointer,
                                                    FfiConverterTypeYrsTransaction.lower(tx),
                                                    FfiConverterString.lower(key), $0)
                }
        )
    }

    public func insert(tx: YrsTransaction, key: String, value: String) {
        try!
            rustCall {
                yniffi_7ef6_YrsMap_insert(self.pointer,
                                          FfiConverterTypeYrsTransaction.lower(tx),
                                          FfiConverterString.lower(key),
                                          FfiConverterString.lower(value), $0)
            }
    }

    public func get(tx: YrsTransaction, key: String) throws -> String {
        return try FfiConverterString.lift(
            rustCallWithError(FfiConverterTypeCodingError.self) {
                yniffi_7ef6_YrsMap_get(self.pointer,
                                       FfiConverterTypeYrsTransaction.lower(tx),
                                       FfiConverterString.lower(key), $0)
            }
        )
    }

    public func remove(tx: YrsTransaction, key: String) throws -> String? {
        return try FfiConverterOptionString.lift(
            rustCallWithError(FfiConverterTypeCodingError.self) {
                yniffi_7ef6_YrsMap_remove(self.pointer,
                                          FfiConverterTypeYrsTransaction.lower(tx),
                                          FfiConverterString.lower(key), $0)
            }
        )
    }

    public func clear(tx: YrsTransaction) {
        try!
            rustCall {
                yniffi_7ef6_YrsMap_clear(self.pointer,
                                         FfiConverterTypeYrsTransaction.lower(tx), $0)
            }
    }
}

public struct FfiConverterTypeYrsMap: FfiConverter {
    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = YrsMap

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> YrsMap {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if ptr == nil {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: YrsMap, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> YrsMap {
        return YrsMap(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: YrsMap) -> UnsafeMutableRawPointer {
        return value.pointer
    }
}

public protocol YrsTextProtocol {
    func format(tx: YrsTransaction, index: UInt32, length: UInt32, attrs: [String: String])
    func append(tx: YrsTransaction, text: String)
    func insert(tx: YrsTransaction, index: UInt32, chunk: String)
    func insertWithAttributes(tx: YrsTransaction, index: UInt32, chunk: String, attrs: [String: String])
    func insertEmbed(tx: YrsTransaction, index: UInt32, content: String)
    func insertEmbedWithAttributes(tx: YrsTransaction, index: UInt32, content: String, attrs: [String: String])
    func getString(tx: YrsTransaction) -> String
    func removeRange(tx: YrsTransaction, start: UInt32, length: UInt32)
    func length(tx: YrsTransaction) -> UInt32
    func observe(delegate: YrsTextObservationDelegate) -> UInt32
    func unobserve(subscriptionId: UInt32)
}

public class YrsText: YrsTextProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    deinit {
        try! rustCall { ffi_yniffi_7ef6_YrsText_object_free(pointer, $0) }
    }

    public func format(tx: YrsTransaction, index: UInt32, length: UInt32, attrs: [String: String]) {
        try!
            rustCall {
                yniffi_7ef6_YrsText_format(self.pointer,
                                           FfiConverterTypeYrsTransaction.lower(tx),
                                           FfiConverterUInt32.lower(index),
                                           FfiConverterUInt32.lower(length),
                                           FfiConverterDictionaryStringString.lower(attrs), $0)
            }
    }

    public func append(tx: YrsTransaction, text: String) {
        try!
            rustCall {
                yniffi_7ef6_YrsText_append(self.pointer,
                                           FfiConverterTypeYrsTransaction.lower(tx),
                                           FfiConverterString.lower(text), $0)
            }
    }

    public func insert(tx: YrsTransaction, index: UInt32, chunk: String) {
        try!
            rustCall {
                yniffi_7ef6_YrsText_insert(self.pointer,
                                           FfiConverterTypeYrsTransaction.lower(tx),
                                           FfiConverterUInt32.lower(index),
                                           FfiConverterString.lower(chunk), $0)
            }
    }

    public func insertWithAttributes(tx: YrsTransaction, index: UInt32, chunk: String, attrs: [String: String]) {
        try!
            rustCall {
                yniffi_7ef6_YrsText_insert_with_attributes(self.pointer,
                                                           FfiConverterTypeYrsTransaction.lower(tx),
                                                           FfiConverterUInt32.lower(index),
                                                           FfiConverterString.lower(chunk),
                                                           FfiConverterDictionaryStringString.lower(attrs), $0)
            }
    }

    public func insertEmbed(tx: YrsTransaction, index: UInt32, content: String) {
        try!
            rustCall {
                yniffi_7ef6_YrsText_insert_embed(self.pointer,
                                                 FfiConverterTypeYrsTransaction.lower(tx),
                                                 FfiConverterUInt32.lower(index),
                                                 FfiConverterString.lower(content), $0)
            }
    }

    public func insertEmbedWithAttributes(tx: YrsTransaction, index: UInt32, content: String, attrs: [String: String]) {
        try!
            rustCall {
                yniffi_7ef6_YrsText_insert_embed_with_attributes(self.pointer,
                                                                 FfiConverterTypeYrsTransaction.lower(tx),
                                                                 FfiConverterUInt32.lower(index),
                                                                 FfiConverterString.lower(content),
                                                                 FfiConverterDictionaryStringString.lower(attrs), $0)
            }
    }

    public func getString(tx: YrsTransaction) -> String {
        return try! FfiConverterString.lift(
            try!
                rustCall {
                    yniffi_7ef6_YrsText_get_string(self.pointer,
                                                   FfiConverterTypeYrsTransaction.lower(tx), $0)
                }
        )
    }

    public func removeRange(tx: YrsTransaction, start: UInt32, length: UInt32) {
        try!
            rustCall {
                yniffi_7ef6_YrsText_remove_range(self.pointer,
                                                 FfiConverterTypeYrsTransaction.lower(tx),
                                                 FfiConverterUInt32.lower(start),
                                                 FfiConverterUInt32.lower(length), $0)
            }
    }

    public func length(tx: YrsTransaction) -> UInt32 {
        return try! FfiConverterUInt32.lift(
            try!
                rustCall {
                    yniffi_7ef6_YrsText_length(self.pointer,
                                               FfiConverterTypeYrsTransaction.lower(tx), $0)
                }
        )
    }

    public func observe(delegate: YrsTextObservationDelegate) -> UInt32 {
        return try! FfiConverterUInt32.lift(
            try!
                rustCall {
                    yniffi_7ef6_YrsText_observe(self.pointer,
                                                FfiConverterCallbackInterfaceYrsTextObservationDelegate.lower(delegate), $0)
                }
        )
    }

    public func unobserve(subscriptionId: UInt32) {
        try!
            rustCall {
                yniffi_7ef6_YrsText_unobserve(self.pointer,
                                              FfiConverterUInt32.lower(subscriptionId), $0)
            }
    }
}

public struct FfiConverterTypeYrsText: FfiConverter {
    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = YrsText

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> YrsText {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if ptr == nil {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: YrsText, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> YrsText {
        return YrsText(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: YrsText) -> UnsafeMutableRawPointer {
        return value.pointer
    }
}

public protocol YrsTransactionProtocol {
    func transactionApplyUpdate(update: [UInt8]) throws
    func transactionEncodeStateAsUpdateFromSv(stateVector: [UInt8]) throws -> [UInt8]
    func transactionEncodeStateAsUpdate() -> [UInt8]
    func transactionEncodeUpdate() -> [UInt8]
    func transactionStateVector() -> [UInt8]
    func transactionGetText(name: String) -> YrsText?
    func transactionGetArray(name: String) -> YrsArray?
    func transactionGetMap(name: String) -> YrsMap?
    func free()
}

public class YrsTransaction: YrsTransactionProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    deinit {
        try! rustCall { ffi_yniffi_7ef6_YrsTransaction_object_free(pointer, $0) }
    }

    public func transactionApplyUpdate(update: [UInt8]) throws {
        try
            rustCallWithError(FfiConverterTypeCodingError.self) {
                yniffi_7ef6_YrsTransaction_transaction_apply_update(self.pointer,
                                                                    FfiConverterSequenceUInt8.lower(update), $0)
            }
    }

    public func transactionEncodeStateAsUpdateFromSv(stateVector: [UInt8]) throws -> [UInt8] {
        return try FfiConverterSequenceUInt8.lift(
            rustCallWithError(FfiConverterTypeCodingError.self) {
                yniffi_7ef6_YrsTransaction_transaction_encode_state_as_update_from_sv(self.pointer,
                                                                                      FfiConverterSequenceUInt8.lower(stateVector), $0)
            }
        )
    }

    public func transactionEncodeStateAsUpdate() -> [UInt8] {
        return try! FfiConverterSequenceUInt8.lift(
            try!
                rustCall {
                    yniffi_7ef6_YrsTransaction_transaction_encode_state_as_update(self.pointer, $0)
                }
        )
    }

    public func transactionEncodeUpdate() -> [UInt8] {
        return try! FfiConverterSequenceUInt8.lift(
            try!
                rustCall {
                    yniffi_7ef6_YrsTransaction_transaction_encode_update(self.pointer, $0)
                }
        )
    }

    public func transactionStateVector() -> [UInt8] {
        return try! FfiConverterSequenceUInt8.lift(
            try!
                rustCall {
                    yniffi_7ef6_YrsTransaction_transaction_state_vector(self.pointer, $0)
                }
        )
    }

    public func transactionGetText(name: String) -> YrsText? {
        return try! FfiConverterOptionTypeYrsText.lift(
            try!
                rustCall {
                    yniffi_7ef6_YrsTransaction_transaction_get_text(self.pointer,
                                                                    FfiConverterString.lower(name), $0)
                }
        )
    }

    public func transactionGetArray(name: String) -> YrsArray? {
        return try! FfiConverterOptionTypeYrsArray.lift(
            try!
                rustCall {
                    yniffi_7ef6_YrsTransaction_transaction_get_array(self.pointer,
                                                                     FfiConverterString.lower(name), $0)
                }
        )
    }

    public func transactionGetMap(name: String) -> YrsMap? {
        return try! FfiConverterOptionTypeYrsMap.lift(
            try!
                rustCall {
                    yniffi_7ef6_YrsTransaction_transaction_get_map(self.pointer,
                                                                   FfiConverterString.lower(name), $0)
                }
        )
    }

    public func free() {
        try!
            rustCall {
                yniffi_7ef6_YrsTransaction_free(self.pointer, $0)
            }
    }
}

public struct FfiConverterTypeYrsTransaction: FfiConverter {
    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = YrsTransaction

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> YrsTransaction {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if ptr == nil {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: YrsTransaction, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> YrsTransaction {
        return YrsTransaction(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: YrsTransaction) -> UnsafeMutableRawPointer {
        return value.pointer
    }
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
public enum YrsChange {
    case added(elements: [String])
    case removed(range: UInt32)
    case retained(range: UInt32)
}

public struct FfiConverterTypeYrsChange: FfiConverterRustBuffer {
    typealias SwiftType = YrsChange

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> YrsChange {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        case 1: return try .added(
                elements: FfiConverterSequenceString.read(from: &buf)
            )

        case 2: return try .removed(
                range: FfiConverterUInt32.read(from: &buf)
            )

        case 3: return try .retained(
                range: FfiConverterUInt32.read(from: &buf)
            )

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: YrsChange, into buf: inout [UInt8]) {
        switch value {
        case let .added(elements):
            writeInt(&buf, Int32(1))
            FfiConverterSequenceString.write(elements, into: &buf)

        case let .removed(range):
            writeInt(&buf, Int32(2))
            FfiConverterUInt32.write(range, into: &buf)

        case let .retained(range):
            writeInt(&buf, Int32(3))
            FfiConverterUInt32.write(range, into: &buf)
        }
    }
}

public func FfiConverterTypeYrsChange_lift(_ buf: RustBuffer) throws -> YrsChange {
    return try FfiConverterTypeYrsChange.lift(buf)
}

public func FfiConverterTypeYrsChange_lower(_ value: YrsChange) -> RustBuffer {
    return FfiConverterTypeYrsChange.lower(value)
}

extension YrsChange: Equatable, Hashable {}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
public enum YrsDelta {
    case inserted(value: String, attrs: [String: String])
    case deleted(index: UInt32)
    case retained(index: UInt32, attrs: [String: String])
}

public struct FfiConverterTypeYrsDelta: FfiConverterRustBuffer {
    typealias SwiftType = YrsDelta

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> YrsDelta {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        case 1: return try .inserted(
                value: FfiConverterString.read(from: &buf),
                attrs: FfiConverterDictionaryStringString.read(from: &buf)
            )

        case 2: return try .deleted(
                index: FfiConverterUInt32.read(from: &buf)
            )

        case 3: return try .retained(
                index: FfiConverterUInt32.read(from: &buf),
                attrs: FfiConverterDictionaryStringString.read(from: &buf)
            )

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: YrsDelta, into buf: inout [UInt8]) {
        switch value {
        case let .inserted(value, attrs):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(value, into: &buf)
            FfiConverterDictionaryStringString.write(attrs, into: &buf)

        case let .deleted(index):
            writeInt(&buf, Int32(2))
            FfiConverterUInt32.write(index, into: &buf)

        case let .retained(index, attrs):
            writeInt(&buf, Int32(3))
            FfiConverterUInt32.write(index, into: &buf)
            FfiConverterDictionaryStringString.write(attrs, into: &buf)
        }
    }
}

public func FfiConverterTypeYrsDelta_lift(_ buf: RustBuffer) throws -> YrsDelta {
    return try FfiConverterTypeYrsDelta.lift(buf)
}

public func FfiConverterTypeYrsDelta_lower(_ value: YrsDelta) -> RustBuffer {
    return FfiConverterTypeYrsDelta.lower(value)
}

extension YrsDelta: Equatable, Hashable {}

public enum CodingError {
    // Simple error enums only carry a message
    case EncodingError(message: String)

    // Simple error enums only carry a message
    case DecodingError(message: String)
}

public struct FfiConverterTypeCodingError: FfiConverterRustBuffer {
    typealias SwiftType = CodingError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CodingError {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        case 1: return try .EncodingError(
                message: FfiConverterString.read(from: &buf)
            )

        case 2: return try .DecodingError(
                message: FfiConverterString.read(from: &buf)
            )

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: CodingError, into buf: inout [UInt8]) {
        switch value {
        case let .EncodingError(message):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(message, into: &buf)
        case let .DecodingError(message):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(message, into: &buf)
        }
    }
}

extension CodingError: Equatable, Hashable {}

extension CodingError: Error {}

private extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        lock()
        defer { self.unlock() }
        return try f()
    }
}

private typealias UniFFICallbackHandle = UInt64
private class UniFFICallbackHandleMap<T> {
    private var leftMap: [UniFFICallbackHandle: T] = [:]
    private var counter: [UniFFICallbackHandle: UInt64] = [:]
    private var rightMap: [ObjectIdentifier: UniFFICallbackHandle] = [:]

    private let lock = NSLock()
    private var currentHandle: UniFFICallbackHandle = 0
    private let stride: UniFFICallbackHandle = 1

    func insert(obj: T) -> UniFFICallbackHandle {
        lock.withLock {
            let id = ObjectIdentifier(obj as AnyObject)
            let handle = rightMap[id] ?? {
                currentHandle += stride
                let handle = currentHandle
                leftMap[handle] = obj
                rightMap[id] = handle
                return handle
            }()
            counter[handle] = (counter[handle] ?? 0) + 1
            return handle
        }
    }

    func get(handle: UniFFICallbackHandle) -> T? {
        lock.withLock {
            leftMap[handle]
        }
    }

    func delete(handle: UniFFICallbackHandle) {
        remove(handle: handle)
    }

    @discardableResult
    func remove(handle: UniFFICallbackHandle) -> T? {
        lock.withLock {
            defer { counter[handle] = (counter[handle] ?? 1) - 1 }
            guard counter[handle] == 1 else { return leftMap[handle] }
            let obj = leftMap.removeValue(forKey: handle)
            if let obj = obj {
                rightMap.removeValue(forKey: ObjectIdentifier(obj as AnyObject))
            }
            return obj
        }
    }
}

// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0

// Declaration and FfiConverters for YrsArrayEachDelegate Callback Interface

public protocol YrsArrayEachDelegate: AnyObject {
    func call(value: String)
}

// The ForeignCallback that is passed to Rust.
private let foreignCallbackCallbackInterfaceYrsArrayEachDelegate: ForeignCallback =
    { (handle: UniFFICallbackHandle, method: Int32, args: RustBuffer, out_buf: UnsafeMutablePointer<RustBuffer>) -> Int32 in
        func invokeCall(_ swiftCallbackInterface: YrsArrayEachDelegate, _ args: RustBuffer) throws -> RustBuffer {
            defer { args.deallocate() }

            var reader = createReader(data: Data(rustBuffer: args))
            try swiftCallbackInterface.call(
                value: FfiConverterString.read(from: &reader)
            )
            return RustBuffer()
            // TODO: catch errors and report them back to Rust.
            // https://github.com/mozilla/uniffi-rs/issues/351
        }

        let cb: YrsArrayEachDelegate
        do {
            cb = try FfiConverterCallbackInterfaceYrsArrayEachDelegate.lift(handle)
        } catch {
            out_buf.pointee = FfiConverterString.lower("YrsArrayEachDelegate: Invalid handle")
            return -1
        }

        switch method {
        case IDX_CALLBACK_FREE:
            FfiConverterCallbackInterfaceYrsArrayEachDelegate.drop(handle: handle)
            // No return value.
            // See docs of ForeignCallback in `uniffi/src/ffi/foreigncallbacks.rs`
            return 0
        case 1:
            do {
                out_buf.pointee = try invokeCall(cb, args)
                // Value written to out buffer.
                // See docs of ForeignCallback in `uniffi/src/ffi/foreigncallbacks.rs`
                return 1
            } catch {
                out_buf.pointee = FfiConverterString.lower(String(describing: error))
                return -1
            }

        // This should never happen, because an out of bounds method index won't
        // ever be used. Once we can catch errors, we should return an InternalError.
        // https://github.com/mozilla/uniffi-rs/issues/351
        default:
            // An unexpected error happened.
            // See docs of ForeignCallback in `uniffi/src/ffi/foreigncallbacks.rs`
            return -1
        }
    }

// FfiConverter protocol for callback interfaces
private enum FfiConverterCallbackInterfaceYrsArrayEachDelegate {
    // Initialize our callback method with the scaffolding code
    private static var callbackInitialized = false
    private static func initCallback() {
        try! rustCall { (err: UnsafeMutablePointer<RustCallStatus>) in
            ffi_yniffi_7ef6_YrsArrayEachDelegate_init_callback(foreignCallbackCallbackInterfaceYrsArrayEachDelegate, err)
        }
    }

    private static func ensureCallbackinitialized() {
        if !callbackInitialized {
            initCallback()
            callbackInitialized = true
        }
    }

    static func drop(handle: UniFFICallbackHandle) {
        handleMap.remove(handle: handle)
    }

    private static var handleMap = UniFFICallbackHandleMap<YrsArrayEachDelegate>()
}

extension FfiConverterCallbackInterfaceYrsArrayEachDelegate: FfiConverter {
    typealias SwiftType = YrsArrayEachDelegate
    // We can use Handle as the FfiType because it's a typealias to UInt64
    typealias FfiType = UniFFICallbackHandle

    public static func lift(_ handle: UniFFICallbackHandle) throws -> SwiftType {
        ensureCallbackinitialized()
        guard let callback = handleMap.get(handle: handle) else {
            throw UniffiInternalError.unexpectedStaleHandle
        }
        return callback
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        ensureCallbackinitialized()
        let handle: UniFFICallbackHandle = try readInt(&buf)
        return try lift(handle)
    }

    public static func lower(_ v: SwiftType) -> UniFFICallbackHandle {
        ensureCallbackinitialized()
        return handleMap.insert(obj: v)
    }

    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        ensureCallbackinitialized()
        writeInt(&buf, lower(v))
    }
}

// Declaration and FfiConverters for YrsArrayObservationDelegate Callback Interface

public protocol YrsArrayObservationDelegate: AnyObject {
    func call(value: [YrsChange])
}

// The ForeignCallback that is passed to Rust.
private let foreignCallbackCallbackInterfaceYrsArrayObservationDelegate: ForeignCallback =
    { (handle: UniFFICallbackHandle, method: Int32, args: RustBuffer, out_buf: UnsafeMutablePointer<RustBuffer>) -> Int32 in
        func invokeCall(_ swiftCallbackInterface: YrsArrayObservationDelegate, _ args: RustBuffer) throws -> RustBuffer {
            defer { args.deallocate() }

            var reader = createReader(data: Data(rustBuffer: args))
            try swiftCallbackInterface.call(
                value: FfiConverterSequenceTypeYrsChange.read(from: &reader)
            )
            return RustBuffer()
            // TODO: catch errors and report them back to Rust.
            // https://github.com/mozilla/uniffi-rs/issues/351
        }

        let cb: YrsArrayObservationDelegate
        do {
            cb = try FfiConverterCallbackInterfaceYrsArrayObservationDelegate.lift(handle)
        } catch {
            out_buf.pointee = FfiConverterString.lower("YrsArrayObservationDelegate: Invalid handle")
            return -1
        }

        switch method {
        case IDX_CALLBACK_FREE:
            FfiConverterCallbackInterfaceYrsArrayObservationDelegate.drop(handle: handle)
            // No return value.
            // See docs of ForeignCallback in `uniffi/src/ffi/foreigncallbacks.rs`
            return 0
        case 1:
            do {
                out_buf.pointee = try invokeCall(cb, args)
                // Value written to out buffer.
                // See docs of ForeignCallback in `uniffi/src/ffi/foreigncallbacks.rs`
                return 1
            } catch {
                out_buf.pointee = FfiConverterString.lower(String(describing: error))
                return -1
            }

        // This should never happen, because an out of bounds method index won't
        // ever be used. Once we can catch errors, we should return an InternalError.
        // https://github.com/mozilla/uniffi-rs/issues/351
        default:
            // An unexpected error happened.
            // See docs of ForeignCallback in `uniffi/src/ffi/foreigncallbacks.rs`
            return -1
        }
    }

// FfiConverter protocol for callback interfaces
private enum FfiConverterCallbackInterfaceYrsArrayObservationDelegate {
    // Initialize our callback method with the scaffolding code
    private static var callbackInitialized = false
    private static func initCallback() {
        try! rustCall { (err: UnsafeMutablePointer<RustCallStatus>) in
            ffi_yniffi_7ef6_YrsArrayObservationDelegate_init_callback(foreignCallbackCallbackInterfaceYrsArrayObservationDelegate, err)
        }
    }

    private static func ensureCallbackinitialized() {
        if !callbackInitialized {
            initCallback()
            callbackInitialized = true
        }
    }

    static func drop(handle: UniFFICallbackHandle) {
        handleMap.remove(handle: handle)
    }

    private static var handleMap = UniFFICallbackHandleMap<YrsArrayObservationDelegate>()
}

extension FfiConverterCallbackInterfaceYrsArrayObservationDelegate: FfiConverter {
    typealias SwiftType = YrsArrayObservationDelegate
    // We can use Handle as the FfiType because it's a typealias to UInt64
    typealias FfiType = UniFFICallbackHandle

    public static func lift(_ handle: UniFFICallbackHandle) throws -> SwiftType {
        ensureCallbackinitialized()
        guard let callback = handleMap.get(handle: handle) else {
            throw UniffiInternalError.unexpectedStaleHandle
        }
        return callback
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        ensureCallbackinitialized()
        let handle: UniFFICallbackHandle = try readInt(&buf)
        return try lift(handle)
    }

    public static func lower(_ v: SwiftType) -> UniFFICallbackHandle {
        ensureCallbackinitialized()
        return handleMap.insert(obj: v)
    }

    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        ensureCallbackinitialized()
        writeInt(&buf, lower(v))
    }
}

// Declaration and FfiConverters for YrsTextObservationDelegate Callback Interface

public protocol YrsTextObservationDelegate: AnyObject {
    func call(value: [YrsDelta])
}

// The ForeignCallback that is passed to Rust.
private let foreignCallbackCallbackInterfaceYrsTextObservationDelegate: ForeignCallback =
    { (handle: UniFFICallbackHandle, method: Int32, args: RustBuffer, out_buf: UnsafeMutablePointer<RustBuffer>) -> Int32 in
        func invokeCall(_ swiftCallbackInterface: YrsTextObservationDelegate, _ args: RustBuffer) throws -> RustBuffer {
            defer { args.deallocate() }

            var reader = createReader(data: Data(rustBuffer: args))
            try swiftCallbackInterface.call(
                value: FfiConverterSequenceTypeYrsDelta.read(from: &reader)
            )
            return RustBuffer()
            // TODO: catch errors and report them back to Rust.
            // https://github.com/mozilla/uniffi-rs/issues/351
        }

        let cb: YrsTextObservationDelegate
        do {
            cb = try FfiConverterCallbackInterfaceYrsTextObservationDelegate.lift(handle)
        } catch {
            out_buf.pointee = FfiConverterString.lower("YrsTextObservationDelegate: Invalid handle")
            return -1
        }

        switch method {
        case IDX_CALLBACK_FREE:
            FfiConverterCallbackInterfaceYrsTextObservationDelegate.drop(handle: handle)
            // No return value.
            // See docs of ForeignCallback in `uniffi/src/ffi/foreigncallbacks.rs`
            return 0
        case 1:
            do {
                out_buf.pointee = try invokeCall(cb, args)
                // Value written to out buffer.
                // See docs of ForeignCallback in `uniffi/src/ffi/foreigncallbacks.rs`
                return 1
            } catch {
                out_buf.pointee = FfiConverterString.lower(String(describing: error))
                return -1
            }

        // This should never happen, because an out of bounds method index won't
        // ever be used. Once we can catch errors, we should return an InternalError.
        // https://github.com/mozilla/uniffi-rs/issues/351
        default:
            // An unexpected error happened.
            // See docs of ForeignCallback in `uniffi/src/ffi/foreigncallbacks.rs`
            return -1
        }
    }

// FfiConverter protocol for callback interfaces
private enum FfiConverterCallbackInterfaceYrsTextObservationDelegate {
    // Initialize our callback method with the scaffolding code
    private static var callbackInitialized = false
    private static func initCallback() {
        try! rustCall { (err: UnsafeMutablePointer<RustCallStatus>) in
            ffi_yniffi_7ef6_YrsTextObservationDelegate_init_callback(foreignCallbackCallbackInterfaceYrsTextObservationDelegate, err)
        }
    }

    private static func ensureCallbackinitialized() {
        if !callbackInitialized {
            initCallback()
            callbackInitialized = true
        }
    }

    static func drop(handle: UniFFICallbackHandle) {
        handleMap.remove(handle: handle)
    }

    private static var handleMap = UniFFICallbackHandleMap<YrsTextObservationDelegate>()
}

extension FfiConverterCallbackInterfaceYrsTextObservationDelegate: FfiConverter {
    typealias SwiftType = YrsTextObservationDelegate
    // We can use Handle as the FfiType because it's a typealias to UInt64
    typealias FfiType = UniFFICallbackHandle

    public static func lift(_ handle: UniFFICallbackHandle) throws -> SwiftType {
        ensureCallbackinitialized()
        guard let callback = handleMap.get(handle: handle) else {
            throw UniffiInternalError.unexpectedStaleHandle
        }
        return callback
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        ensureCallbackinitialized()
        let handle: UniFFICallbackHandle = try readInt(&buf)
        return try lift(handle)
    }

    public static func lower(_ v: SwiftType) -> UniFFICallbackHandle {
        ensureCallbackinitialized()
        return handleMap.insert(obj: v)
    }

    public static func write(_ v: SwiftType, into buf: inout [UInt8]) {
        ensureCallbackinitialized()
        writeInt(&buf, lower(v))
    }
}

private struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

private struct FfiConverterOptionTypeYrsArray: FfiConverterRustBuffer {
    typealias SwiftType = YrsArray?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeYrsArray.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeYrsArray.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

private struct FfiConverterOptionTypeYrsMap: FfiConverterRustBuffer {
    typealias SwiftType = YrsMap?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeYrsMap.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeYrsMap.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

private struct FfiConverterOptionTypeYrsText: FfiConverterRustBuffer {
    typealias SwiftType = YrsText?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeYrsText.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeYrsText.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

private struct FfiConverterSequenceUInt8: FfiConverterRustBuffer {
    typealias SwiftType = [UInt8]

    public static func write(_ value: [UInt8], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterUInt8.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [UInt8] {
        let len: Int32 = try readInt(&buf)
        var seq = [UInt8]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            try seq.append(FfiConverterUInt8.read(from: &buf))
        }
        return seq
    }
}

private struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            try seq.append(FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

private struct FfiConverterSequenceTypeYrsChange: FfiConverterRustBuffer {
    typealias SwiftType = [YrsChange]

    public static func write(_ value: [YrsChange], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeYrsChange.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [YrsChange] {
        let len: Int32 = try readInt(&buf)
        var seq = [YrsChange]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            try seq.append(FfiConverterTypeYrsChange.read(from: &buf))
        }
        return seq
    }
}

private struct FfiConverterSequenceTypeYrsDelta: FfiConverterRustBuffer {
    typealias SwiftType = [YrsDelta]

    public static func write(_ value: [YrsDelta], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeYrsDelta.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [YrsDelta] {
        let len: Int32 = try readInt(&buf)
        var seq = [YrsDelta]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            try seq.append(FfiConverterTypeYrsDelta.read(from: &buf))
        }
        return seq
    }
}

private struct FfiConverterDictionaryStringString: FfiConverterRustBuffer {
    public static func write(_ value: [String: String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for (key, value) in value {
            FfiConverterString.write(key, into: &buf)
            FfiConverterString.write(value, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String: String] {
        let len: Int32 = try readInt(&buf)
        var dict = [String: String]()
        dict.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            let key = try FfiConverterString.read(from: &buf)
            let value = try FfiConverterString.read(from: &buf)
            dict[key] = value
        }
        return dict
    }
}

/**
 * Top level initializers and tear down methods.
 *
 * This is generated by uniffi.
 */
public enum YniffiLifecycle {
    /**
     * Initialize the FFI and Rust library. This should be only called once per application.
     */
    func initialize() {}
}
